// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrxgwszcoetuvfbiqarl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyeGd3c3pjb2V0dXZmYmlxYXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzQzOTMsImV4cCI6MjA3MjQ1MDM5M30.5Wv9OTivFploGjE5KvZ6vjI-r-CxfHSU1PLoEF62fvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});